credentials:
  usernames:
    kashish:
      email: kashishah2804@gmail.com
      name: Kashish Shah
      password: "$2b$12$qWY6aN.KcQoR3N/VoHaTRuLTFKv6MH6FiXBdYhSlWkCHaVLx9gZny"  # password: pass1234
