credentials:
  usernames:
    kashish:
      email: kashishah2804@gmail.com
      name: Kashish Shah
      password: "$2b$12$qWY6aN.KcQoR3N/VoHaTRuLTFKv6MH6FiXBdYhSlWkCHaVLx9gZny"  # pass1234
    vidushi:
      email: vidushidhakad@gmail.com
      name: Vidushi Dhakad
      password: "$2b$12$fSL6qI/xU1mmp3WxIk7bnOzWvMC/fXNfSTJ8QHt.B1Xzy5rIptH1K"  # vid123
    pavitra:
      email: dasspavitra2007@example.com
      name: Pavitra Dass
      password: "$2b$12$rAFM2/vGxME9IaLjlSTZ6OvL2a9HqJENyJK7H2BOpQ.CGKx6QhwV."  # pav123
    sanya:
      email: jhaverisanya@gmail.com
      name: Sanya Jhaveri
      password: "$2b$12$YZABccWTZItPh/rsFZ0uJOXJq1U5biZPNXuPbFbcKaXk3ZsMQ.NDK"  # san123
