credentials:
  usernames:
    kashish:
      email: kashishah2804@gmail.com
      name: Kashish Shah
      password: "$2b$12$qWY6aN.KcQoR3N/VoHaTRuLTFKv6MH6FiXBdYhSlWkCHaVLx9gZny"  # pass1234
    vidushi:
      email: vidushidhakad@gmail.com
      name: Vidushi Dhakad
      password: "$2b$12$MlYxUvFy2PCAvFl2ukXKDuq3MgXLZ4MnY4IJYpNwGBGMLpmDCTkga"  # vid123
    pavitra:
      email: dasspavitra2007@example.com
      name: Pavitra Dass
      password: "$2b$12$hCoxn3x9yk1djC7M9RGh/ebnNElkCu0Bt4LMVn2huYkXtG5M2TKiK"  # pav123
    sanya:
      email: jhaverisanya@gmail.com
      name: Sanya Jhaveri
      password: "$2b$12$ZkgYdsAXZ86YAU7rWJDbO.Nc46qG0bRLF1KnKbNEXeZByhMKdx4f6"  # san123
